---
version: 2.1

orbs:
  go: circleci/go@0.2.0

jobs:
  test:
    parameters:
      go_version:
        type: string
      use_gomod_cache:
        type: boolean
        default: true
    docker:
    - image: circleci/golang:<< parameters.go_version >>
    working_directory: /go/src/github.com/prometheus/common
    steps:
    - checkout
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/load-cache:
            key: v1-go<< parameters.go_version >>
    - run: make test
    - run: cd sigv4 && make test
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/save-cache:
            key: v1-go<< parameters.go_version >>
    - store_test_results:
        path: test-results
  test-assets:
    parameters:
      go_version:
        type: string
      use_gomod_cache:
        type: boolean
        default: true
    docker:
    - image: circleci/golang:<< parameters.go_version >>
    working_directory: /go/src/github.com/prometheus/common/assets
    steps:
    - checkout
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/load-cache:
            key: v1-go<< parameters.go_version >>
    - run: make test
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/save-cache:
            key: v1-go<< parameters.go_version >>
    - store_test_results:
        path: ../test-results
  style:
    parameters:
      go_version:
        type: string
      use_gomod_cache:
        type: boolean
        default: true
    docker:
    - image: circleci/golang:<< parameters.go_version >>
    working_directory: /go/src/github.com/prometheus/common
    steps:
    - checkout
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/load-cache:
            key: v1-go<< parameters.go_version >>
    - run: make style
    - run: cd sigv4 && make style
    - run: cd assets && make style
    - when:
        condition: << parameters.use_gomod_cache >>
        steps:
        - go/save-cache:
            key: v1-go<< parameters.go_version >>
    - store_test_results:
        path: test-results

workflows:
  version: 2
  tests:
    jobs:
    # Supported Go versions are synced with github.com/prometheus/client_golang.
    - test:
        name: go-<< matrix.go_version >>
        matrix:
          parameters:
            go_version: ["1.13", "1.14", "1.15", "1.16", "1.17"]
    - test-assets:
        name: assets-go-<< matrix.go_version >>
        matrix:
          parameters:
            go_version: ["1.17"]
    - style:
        name: style
        go_version: "1.17"
